name: We Are Thought Fox
markdown: kramdown
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Setup
title:               We Are Thought Fox
description:         'We are strategic communications firm that provides counsel to governments, companies and successful individuals.'
tagline:             Strategic communication
url:                 https://www.wearethoughtfox.com
logo:                /images/LOGO-RGB.png
tel:                 +971552810637
email:               hello@wearethoughtfox.com
calltoaction:        "Get in touch"

collections:
  work:
    output: true
    permalink: /:collection/:name
  blog:
    output: true
    permalink: /:collection/:name

plugins:
  - jekyll-seo-tag

# Defaults
defaults:
  - scope:
      path: ""
    values:
      image: /images/LOGO-RGB.png
