name: We Are Thought Fox
markdown: kramdown
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Setup
title:               We Are Thought Fox
description:         "A digital studio 👽 making the web 💞 with an interdisciplinary approach 🦄"
tagline:             Making the web
url:                 https://www.wearethoughtfox.com
logo:                /images/LOGO-RGB.png
tel:                 +971552810637
email:               hello@wearethoughtfox.com
calltoaction:        "Get in touch"
footer:              "We Are Thought Fox Ltd, Registered in England and Wales, no. 8051628."
analytics:           39223787

collections:
  work:
    output: true
    permalink: /:collection/:slug
  blog:
    output: true
    permalink: /:collection/:slug

plugins:
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-sitemap

pagination:
  enabled: true
  collection: 'blog'
  per_page: 5
  permalink: '/page/:num/'
  sort_reverse : true

include:
  - _pages

# Defaults
defaults:
  - scope:
      path: ""
    values:
      image: /images/LOGO-RGB.png
  - scope:
      path: '_pages'
    values:
      permalink: /:basename/

navigation:
 - title: Work
   url: /work
 - title: Info
   url: /info
